spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-0
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect